version: '3.2'

services:
    app:
        image: "oven/bun"
        entrypoint: []
        command: "/bin/sh -c 'bun install && bun dev --host 0.0.0.0'"
        ports: ["5173:5173"]
        volumes: ["./:/home/bun/app"]
        environment:
            - HOST=0.0.0.0
